citycoins/contracts

tests/run-tests.sh
Changed the name of the contract to the correct one
Converted all relative file paths to be relative to `run-test.sh` script not to execution path.
Improved output readability.
=> Fixed failing testing script.

src/citycoin-client.ts, tests/citycoin_test.ts
This PR introduces more Clarinet-based tests that covers read-only and public functions.
Only `claim-token-reward` is not covered with tests, because I don't know if it is possible to control what `(get-block-info? vrf-seed stacks-block)` will return, therefore I can't create stable tests for it.
=> Feat: Add tests for read-only and public functions

contracts/citycoin.clar, src/citycoin-client.ts, tests/citycoin_test.ts, tests/test-poxl.clar
This PR contains changes that optimize cost of execution `mine-tokens` function.
I replaced very expensive `has-mined-in-list` function that uses `fold` to simulate loop and check if miner already mined in selected block or not, with much faster and least expensive `has-mined` which uses `map-get` to achieve the same result.
As a consequence of this modification I had to introduce new map `miners-block-commitment` which stores information if miner committed anything at specific block height or not.
Execution costs were acquired as follows:
```sh
$ npm run clarinet:console
> (contract-call? .citycoin register-miner)
> ::advance_chain_tip 200
> ::get_costs (contract-call? .citycoin mine-tokens u200)
```
**BEFORE**
```
+----------------------+-----------+------------+
| …
```
=> Optimize mine-tokens execution costs

src/citycoin-client.ts
This PR contains changes that fix broken `can-mine-tokens` interface between JS and clarity.
=> Fix broken `can-mine-tokens` interfact between js and clarity

contracts/citycoin.clar, contracts/sip-10-ft-standard.clar, scripts/clarinet-prepare.sh, src/citycoin-client.ts, tests/citycoin_test.ts
One more small update, closes #53 per [this issue comment](https://github.com/stacksgov/sips/pull/5#issuecomment-850859527)
=> Fix SIP-010 Names V2

contracts/citycoin.clar, src/citycoin-client.ts, tests/citycoin_test.ts
This PR adds optional memo field to `mine-tokens` function that allows miners to attach custom 34 bytes long message to their mining transaction.
Memo length is set to 34 bytes, to keep it consistent with memo's used in other functions.
close #29
=> Add optional memo to mine-tokens function

contracts/citycoin.clar, src/citycoin-client.ts, tests/citycoin_test.ts
This PR introduces new public function `set-token-uri` that allows contract owner and only contract owner to change token uri.
close #42
=> Allow owner to change token uri to new one or none

contracts/citycoin.clar, contracts/test_addons/citycoin.clar, src/citycoin-client.ts, tests/citycoin_test.ts
This PR introduces a function `set-city-wallet` that allows city wallet owner and only city wallet owner to change its address to new one.
To complement it `get-city-wallet` has been added as well.
Additionally `set-city-wallet` function used in test add-on has been renamed to `set-city-wallet-unsafe` as it doesn't check who calls it and should be used only in test arrange process.
closes #51
=> Allow city wallet owner to change it to new one

contracts/citycoin.clar
In commit 14ebfce the token name was changed prematurely and broke tests. This PR reverts the status through an additional commit versus a `git revert` based on recommendations in the [git documentation](https://git-scm.com/docs/git-revert.html) and [linked how-to](https://github.com/git/git/blob/master/Documentation/howto/revert-a-faulty-merge.txt).
=> Revert fungible token name change

Clarinet.toml, contracts/city_wallet.clar, contracts/citycoin.clar, contracts/malicious.clar, tests/citycoin_test.ts
It is probably prudent to add a check to ensure that `set-city-wallet` cannot be called through another contract. This vector, although unlikely to be pulled off, could allow a malicious contract to "trick" the city wallet principal into changing the city wallet. Such an action would not be blocked by post conditions.
By default `contract-caller` is set to the same as `tx-sender`. This kind of check is also in `pox.clar`. In the PoX contract, there is a method for allowing only specific contract callers to stack on behalf of a user, but this is likely not necessary for citycoin.
**Warning:** I have not ran tests, as I had issues getting them to run. Thus, there are also no tests for this added check.
=> fix: prevent contracts from calling set-city-wallet

Clarinet.toml, contracts/citycoin-lifecycle-trait.clar, contracts/citycoin.clar
This PR introduces lifecycle trait contract, that defines 3 functions that other contracts we want to be upgradable and/or have functionality that allows to startup or shutdown them immediately or in the future.
Implementation in `citycoin` contract doesn't have any tests, as main logic for `startup` and `shutdown` functions will be created in separate PR.
Close #112
=> Add lifecycle trait + initial implementation

.github/codecov.yml, .github/workflows/test-contract.yaml, README.md, contracts/citycoin-core-v1.clar
Given the fact this still wasn't working, I found some documentation that referenced the bash uploader and v1 action being phased out in favor of this one. Opening this PR to test - still a WIP! :construction: 
Also reduces the top threshold from 100 to 90% coverage for all green.
And updates "Test Contract" to "Contract Tests", looks better in the readme badge.
=> Testing new codecov uploader v2

contracts/citycoin-core-v1.clar, contracts/clarinet/citycoin-core-v1.clar, src/core-client.ts, tests/citycoin-core-v1.test.ts
Add mining over multiple blocks.
Miners can mine up to 200 blocks at a time, and pick different amount fore each one of them. 
Mining 200 blocks might fail due to executions costs being to high, but Stacks 2.1 should (in theory) solve that.
close #129
=> Add mining over multiple blocks

contracts/citycoin-core-v1.clar, contracts/clarinet/citycoin-core-v1.clar, src/core-client.ts, tests/citycoin-core-v1.test.ts
This PR introduces read-only function `is-block-winner` that returns `true` if user is a block winner, and `false` when he is not.
It doesn't check if user can claim the reward - just tells if user is a block winner or not.
=> Add is-block-winner function

contracts/citycoin-auth.clar, contracts/citycoin-core-v1.clar, contracts/citycoin-core-v2.clar, contracts/citycoin-token.clar, contracts/clarinet/citycoin-auth.clar, contracts/clarinet/citycoin-core-v1.clar, contracts/clarinet/citycoin-core-v2.clar, contracts/clarinet/citycoin-token.clar, contracts/test_addons/citycoin-auth.clar
Main intent for this PR is to clean up our contract in a way that they won't have unnecessary occurrences of `CityCoin` or `CityCoins` phrase. Especially in variable, map and function names.
=> Chore: Remove CityCoin phrase from contracts

contracts/citycoin-auth.clar, contracts/clarinet/citycoin-auth.clar, contracts/clarinet/citycoin-core-v1.clar, src/auth-client.ts, tests/citycoin-auth.test.ts
This PR introduces function, that can be used to replace approver with new one using voting mechanism.
Job parameters:
- `oldApprover` - old approver address (principal)
- `newApprover` - new approver address (principal)
=> Add execute-replace-approver-job()

contracts/citycoin-core-v1.clar, contracts/clarinet/citycoin-core-v1.clar, tests/citycoin-core-v1.test.ts
Based on this TX `mine-many` wasn't checking if contract is active the same way `mine-tokens` was:
https://explorer.stacks.co/txid/0x254fd154953266762f765f3e44e5854382d1c6ac90b04f0d5b393bb610d8daa5
This PR fixes it by adding the same guard and related tests.
=> Add check if contract is active to mine-many

contracts/citycoin-token.clar, contracts/clarinet/citycoin-core-v1.clar, contracts/clarinet/citycoin-token.clar, contracts/test_addons/citycoin-core-v1.clar, models/core.model.ts, models/token.model.ts, tests/citycoin-token.test.ts
This PR removes restriction we imposed on `burn` function and unlocks it for all token owners.
`ft-burn` requires a post-conditions if transaction that executes it is submitted in `deny` mode, therefore guarding it with `tx-sender` is sufficient and using `contract-caller` instead would be excessive.
Because `burn` will be open for everyone we no longer need `test-burn` function in `core` contract addon so it has been removed.
close #149
=> Unlock burn function for all token owners

contracts/citycoin-core-v1.clar, contracts/clarinet/citycoin-core-v1.clar, tests/citycoin-core-v1.test.ts
PR introduces printed tuple with first and last block mined by miner while calling `mine-many` function.
It will make our contract a little bit more verbose and will help users to verify which block they are mining.
Because `print` is treated as event I had adjust few existing tests by increasing number of expected events by 1.
close #151
=> Add printing tuple with first and last block mined while calling mine-many

contracts/citycoin-core-v1.clar, contracts/clarinet/citycoin-core-v1.clar, tests/citycoin-core-v1.test.ts
PR introduces printed tuple with first and last stacking cycle used while calling `stack-tokens`.
It will make our contract a little bit more verbose and will help users to verify what is their first reward cycle, and when they'll be able to get back their tokens.
Just like in #153 I had to adjust few existing tests, by increasing number of expected events by 1.
close #150
=> Add printing tuple with first and last stacking cycle

contracts/NewYorkCityCoin/auth.clar, contracts/NewYorkCityCoin/core-v1.clar, contracts/NewYorkCityCoin/token.clar
NYCCoin contracts deployer: `SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5`
NYC city wallet: `SM18VBF2QYAAHN57Q28E2HSM15F6078JZYZ2FQBCX`
We gonna reuse all traits and VRF contract (all deployed by `SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27`)
Approvers wallet addresses remain unchanged.
=> Add NYCCoin contracts

.github/codecov.yml, contracts/MiamiCoin/auth.clar, contracts/MiamiCoin/core-v1.clar, contracts/MiamiCoin/token.clar, contracts/NewYorkCityCoin/auth.clar, contracts/NewYorkCityCoin/core-v1.clar, contracts/NewYorkCityCoin/token.clar, package.json
This PR corrects a few spots where it was listed as `1.0.2` instead of `1.2.0`.
Also removes an unused contract reference from the codecov.yml file.
After this one we can create the annotated tag on the main branch prior to any protocol changes if the vote passes.
=> Fix version numbering

contracts/MiamiCoin/core-v1.clar, contracts/NewYorkCityCoin/core-v1.clar, contracts/citycoin-core-v1.clar, contracts/citycoin-core-v2.clar, contracts/clarinet/citycoin-core-v1.clar, contracts/clarinet/citycoin-core-v2.clar
There were a few unused variables in `stack-tokens-closure`, this PR removes them from all core contract instances.
=> Remove unused variables

README.md
This PR updates the README to reflect using the new `develop` branch when submitting PRs, and will enforce the new workflow for all changes after `v1.1.0`.
=> Add `develop` branch

README.md, tests/cities/mia/miamicoin-auth-contract-management.test.ts, tests/cities/nyc/newyorkcitycoin-auth-contract-management.test.ts, tests/core/citycoin-auth-contract-management.test.ts
This PR makes a small change to make the test output more consistent. A successful function call should start with `succeeds` and a failed function call should start with `faills with ERR_NAME`.
Also updates the readme based on the new test structure.
=> Replace `throws` with `fails with` in tests

contracts/cities/mia/local/miamicoin-core-v2.clar, contracts/cities/nyc/local/newyorkcitycoin-core-v2.clar, models/cities/mia/miamicoin-core-v2.model.ts, models/cities/nyc/newyorkcitycoin-core-v2.model.ts, tests/cities/mia/core/core-v2/miamicoin-core-v2-city-wallet-management.test.ts, tests/cities/mia/core/core-v2/miamicoin-core-v2-mining-claims.test.ts, tests/cities/mia/core/core-v2/miamicoin-core-v2-mining.test.ts, tests/cities/mia/core/core-v2/miamicoin-core-v2-registration.test.ts, tests/cities/mia/core/core-v2/miamicoin-core-v2-stacking-claims.test.ts, tests/cities/mia/core/core-v2/miamicoin-core-v2-stacking.test.ts, tests/cities/mia/core/core-v2/miamicoin-core-v2-token-configuration.test.ts, tests/cities/nyc/core/core-v2/newyorkcitycoin-core-v2-city-wallet-management.test.ts, tests/cities/nyc/core/core-v2/newyorkcitycoin-core-v2-mining-claims.test.ts, tests/cities/nyc/core/core-v2/newyorkcitycoin-core-v2-mining.test.ts, tests/cities/nyc/core/core-v2/newyorkcitycoin-core-v2-registration.test.ts, tests/cities/nyc/core/core-v2/newyorkcitycoin-core-v2-stacking-claims.test.ts, tests/cities/nyc/core/core-v2/newyorkcitycoin-core-v2-stacking.test.ts, tests/cities/nyc/core/core-v2/newyorkcitycoin-core-v2-token-configuration.test.ts
This PR separates the activation block from the target block to start mining and stacking, so that:
- MIA/NYC can be set with an activation block in the past, making the emissions schedule continue where we left off (this affects the coinbase thresholds)
- MIA/NYC can set a target block for mining/stacking, so that if a delay is needed when shutting down V1, it is set independently of the activation block
=> Community Upgrade: upgrade/activation flow

contracts/cities/mia/local/miamicoin-core-v2.clar, contracts/cities/nyc/local/newyorkcitycoin-core-v2.clar, models/cities/mia/miamicoin-core-v2.model.ts, models/cities/nyc/newyorkcitycoin-core-v2.model.ts, tests/cities/mia/core/core-v2/miamicoin-core-v2-mining-claims.test.ts, tests/cities/mia/core/core-v2/miamicoin-core-v2-mining.test.ts, tests/cities/mia/core/core-v2/miamicoin-core-v2-registration.test.ts, tests/cities/mia/core/core-v2/miamicoin-core-v2-stacking-claims.test.ts, tests/cities/mia/core/core-v2/miamicoin-core-v2-stacking.test.ts, tests/cities/mia/core/core-v2/miamicoin-core-v2-token-configuration.test.ts, tests/cities/mia/upgrade/miamicoin-core-v1-v2.test.ts, tests/cities/nyc/core/core-v2/newyorkcitycoin-core-v2-mining-claims.test.ts, tests/cities/nyc/core/core-v2/newyorkcitycoin-core-v2-mining.test.ts, tests/cities/nyc/core/core-v2/newyorkcitycoin-core-v2-registration.test.ts, tests/cities/nyc/core/core-v2/newyorkcitycoin-core-v2-stacking-claims.test.ts, tests/cities/nyc/core/core-v2/newyorkcitycoin-core-v2-stacking.test.ts, tests/cities/nyc/core/core-v2/newyorkcitycoin-core-v2-token-configuration.test.ts, tests/cities/nyc/upgrade/newyorkcitycoin-core-v1-v2.test.ts
This PR updates the activation delay in the `core-v2` contracts from 150 blocks to 0 blocks.
This way mining can begin as soon as 20 users register, following the shutdown of the `core-v1` contracts.
=> Update activation delay
