citycoins/contracts

citycoin.clar, tests/run-tests.sh, tests/sip-10-ft-standard.clar, tests/test-poxl.clar
Added SIP-010 fungible token trait implementation and updated existing test suite.
Blocks in test suite are shifted by 1 because one block is consumed by trait contract deployment.
Should be merged after: https://github.com/citycoins/citycoin/pull/11
close #1
=> Add SIP-010 fungible token trait implementation

contracts/test_addons/citycoin.clar, package.json, tests/citycoin_test.ts, tests/test-poxl.clar
=> fix: incorrect ft name and broken test

contracts/citycoin.clar
=> Remove redundant `asserts!`

citycoin-prd.md
=> convert references into apa citations

Clarinet.toml, contracts/citycoin.clar, contracts/sip-10-ft-standard.clar, scripts/clarinet-prepare.sh
This PR bumps SIP-010 trait to its latest version.
close #22
=> chore: bump sip-010 trait to its latest version

citycoin-prd.md, contracts/citycoin.clar, contracts/test_addons/citycoin.clar, src/citycoin-client.ts, tests/citycoin_test.ts
This PR increase mining activation threshold from 1 to 20 and add the possibility to set its value to any value during the tests.
fix #41
=> Increase mining activation threshold to 20

contracts/citycoin.clar, contracts/sip-10-ft-standard.clar, src/citycoin-client.ts, tests/citycoin_test.ts
=> Fix SIP-010 implementation

contracts/citycoin.clar, contracts/sip-10-ft-standard.clar, scripts/clarinet-prepare.sh, src/citycoin-client.ts
This closes #53 (again) with the correct info per [this comment and new deployment](https://github.com/stacksgov/sips/pull/5#issuecomment-850560086) of the SIP-010 traits
=> Fix SIP-010 references

contracts/citycoin.clar
Adds some read only functions around miner registration
=> Add read only functions for UI

contracts/citycoin.clar, src/citycoin-client.ts, tests/citycoin_test.ts
This PR allows miners to add 34 bytes long memo message to their registration TX.
close #38
=> Add optional memo to miner registration

contracts/citycoin.clar
=> Add read only for registered miners nonce

README.md, citycoin-prd.md
Some quick updates following the launch of https://citycoins.co
=> readme and prd updates

docs/miamicoin-mining-and-stacking-guide.md
This PR adds a quick guide on how to activate, mine, and stack MiamiCoins.
=> Add documentation

src/citycoin-client.ts, tests/citycoin_test.ts
Updated clarinet library to 0.10.0 and fixed all errors caused by this update.
=> bump clarinet library version

contracts/citycoin.clar
This PR reduces number of operations performed while executing `fold` function, by using input list with number of elements that match number of miners in a block.
In blocks with small number of miners it reduces execution costs from 4.27% to ~2.07%, and in blocks where we have 128 or almost 128 miners execution costs are either exactly the same as they were or a slightly higher: 6.67% -> 6.69% 
Close #91
=> Add map with 128 lists to reduce fold operatons

contracts/citycoin.clar, src/citycoin-client.ts, tests/citycoin_test.ts, tests/test-poxl.clar
=> Renamed claim-token-reward function to claim-mining-reward

citycoin-prd.md
This PR updates the PRD based on the latest designs and adds links to additional information.
=> Update product requirements document

contracts/citycoin-core-v1.clar, contracts/clarinet/citycoin-core-v1.clar, src/core-client.ts, tests/citycoin-core-v1.test.ts
Add can-claim-mining-reward function
=> Add can-claim-mining-reward function

contracts/Tardis/citycoin-tardis-v2-mainnet.clar
Matches deployed version:
https://explorer.stacks.co/txid/0xc91bf66aa4282533a3b392c0e22071d5bdf26ac6b8eb62392a307961ba0d723e?chain=mainnet
=> Add missing comment

contracts/Vote/citycoin-vote-v1-mainnet.clar, contracts/citycoin-vote-v1.clar, contracts/clarinet/citycoin-vote-v1.clar, models/vote.model.ts, tests/citycoin-vote-v1.test.ts
These are the final changes before deployment!
=> Prep CCIP-011 mainnet contract

Clarinet.toml, settings/Devnet.toml
While trying to test Citycoins with Orchestra, I noticed that the project was unusable on a Devnet setup for a few reasons.
I'll make some changes to Clarinet but meanwhile, we can also fix this by updating the different manifests of that project.
=> fix: update Clarinet.toml and Devnet.toml

.github/codecov.yml, .github/workflows/test-contract.yaml, contracts/core/local/citycoin-token.clar, models/token.model.ts
This adds the contract testing and codecov results to the `develop` branch and related PRs.
=> Add develop branch to workflow

.vscode/extensions.json
Just a minor thing I noticed when testing your contracts.
=> Fix VSCode recommended Clarity extensions
